name: ESLint
on: pull_request
jobs:
  eslint:
    name: Run eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: yarn
      - run: yarn install
      - run: yarn eslint