name: Test
on: pull_request
jobs:
  test:
    name: Run test:ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: '14.x'
          cache: yarn
      - run: yarn install
      - run: yarn test:ci